<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
    ?>
    <?php if ($activePage['depth'] !== 0): ?>
        <!--    <nav class="breadcrumbs">-->
        <?php //echo $nav->breadcrumbs(); ?><!--</nav>-->
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
        <!--    <nav class="sub-menu">-->
        <?php //echo $nav->menu()->renderSubMenu(); ?><!--</nav>-->
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>

<?php
$pageSlug = $page->slug();

if ($pageSlug == "home" || $pageSlug == 'index') {
    $siteTitle = $this->themeSetting('landing_page_name');
    $landingText = $this->themeSetting('landing_page_text');
    echo $this->partial("partials/landing-page-block.phtml", ["title" => $siteTitle, "text" => $landingText]);
} else if( $pageSlug == "explore") {
    $siteTitle = "Explore" . $this->themeSetting("site_name");
    $landingText = $this->content;
    echo $this->partial("explore.phtml", ["title" => $siteTitle, "text" => $landingText]);
} 
else {
    echo $this->content;
}

?>

<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
    <?php echo $this->sitePagePagination(); ?>
<?php endif; ?>