<?php
$translate = $this->plugin('translate');
?>
<nav class="pagination" role="navigation">
    <?php if ($totalCount): ?>
        <form method="GET" action="">
            <?php echo $this->queryToHiddenInputs(['page']); ?>
            <span>Page</span>
            <input type="text" name="page" class="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
            <span class="page-count">
                <?php echo sprintf($translate('of %s'), $pageCount); ?>
            </span>
        </form>

        <?php if ($currentPage != 1): ?>
            <?php echo $this->hyperlink('', $previousPageUrl, ['class' => 'previous explore-left button', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
        <?php else: ?>
            <span class="previous explore-left button inactive"></span>
        <?php endif; ?>

        <?php if ($currentPage < $pageCount): ?>
            <?php echo $this->hyperlink('', $nextPageUrl, ['class' => 'next explore-right button', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
        <?php else: ?>
            <span class="next explore-right button inactive"></span>
        <?php endif; ?>

        <span class="row-count">
            <?php if ($totalCount > 1): ?>
                <?php echo sprintf('%s results', $totalCount); ?>
            <?php else: ?>
                <?php echo sprintf('%s result', $totalCount); ?>
            <?php endif; ?>
        </span>
        <span class="viewToggle">
            <a id="viewToggle" data-view="cards">Switch to List View</a>
        </span>
    <?php else: ?>
        <?php echo '<div class="zero-results">No results</div>'; ?>
    <?php endif; ?>
</nav>