<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form">
    <input type="text" title='Search' name="fulltext_search" value="<?php echo $searchValue; ?>" placeholder="<?php echo $translate('Search...'); ?>">
    <button type="submit" alt="search" title="Search"><?php echo 'SEARCH'; ?></button>
</form>
