<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$this->htmlElement('body')->appendAttribute('class', 'index search');
?>

<?php echo $this->pageTitle(sprintf($translate('Search results for: %s'), $query), $level=2); ?>

<?php if (empty($results)) : ?>
    <p><?php echo $translate('No result found'); ?></p>
<?php else : ?>
    <?php
    $resourceLabels = [
        'site_pages' => 'Site pages', // @translate
        'items' => 'Items', // @translate
        'item_sets' => 'Item sets', // @translate
        'media' => 'Media', // @translate
    ];
    $resourceControllers = [
        'site_pages' => 'page',
        'items' => 'item',
        'item_sets' => 'item-set',
        'media' => 'media',
    ];
    ?>
    <?php foreach ($results as $resourceName => $result) : ?>
<div class="<?php echo $resourceName; ?> results">
    <h2><?php echo $translate($resourceLabels[$resourceName]); ?></h2>
    <ul class="resource-list list">
        <?php foreach ($result['resources'] as $resource) : ?>
            <?php if ('site_pages' === $resourceName) { ?>
                <li class="page resource">
                    <?php
                    $linkPage = sprintf(
                        '<div class="resource-info"><div class="resource-name">%s</div></div>',
                        $resource->title()
                    );
                    echo $resource->linkRaw($linkPage, null, ['class' => 'resource-link']);
                    ?>
                </li>
            <?php } else {
                echo $this->partial(
                    'common/resource-list-item',
                    [
                        'resource' => $resource,
                    ]
                );
            } ?>
        <?php endforeach; ?>
    </ul>
        <?php if ($result['total'] > 10) : ?>
            <?php echo $hyperlink(
                sprintf($translate('View all %s (%s total)'), strtolower($resourceLabels[$resourceName]), $result['total']),
                $url(
                    'site/resource',
                    ['controller' => $resourceControllers[$resourceName], 'action' => 'browse'],
                    ['query' => ['fulltext_search' => $query]],
                    true
                )
            ); ?>
        <?php else : ?>
            <?php echo sprintf(
                '<p>Showing all relevant %s (%s total)</p>',
                strtolower($resourceLabels[$resourceName]),
                $result['total']
            ); ?>
        <?php endif; ?>
</div>
    <?php endforeach; ?>
<?php endif; ?>
