<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file">
    <div class="attachments">
<?php foreach ($this->attachments as $attachment) : ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item) :
        ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media) :
            echo $media->render([
                'thumbnailType' => $thumbnailType,
                'link' => $link,
            ]);
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title') : ?>
        <div class="caption"><?php echo $item->link($item->displayTitle()); ?></div>
        <?php elseif ($showTitleOption == 'file_name') : ?>
        <div class="caption"><?php echo $media->displayTitle(); ?></div>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption) :
        ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
    </div>
</div>
