<footer>
<div class="wrap-outer-footer layout-band">
    <div class="wrap-footer footer-slim">
        <div class="footer-main" aria-label="MIT Libraries footer">
            <div class="identity">
                <div class="wrap-logo-lib">
                    <a href="https://storia.dh.unica.it/asmsa/" class="logo-mit-lib" alt="ASMSA">
                        <span class="sr">MIT Libraries home</span>
                        <img src="https://storia.dh.unica.it/asmsa/sites/default/files/logo_asmsa.png" alt="ASMSA">
                    </a>
                </div>
                <div class="wrap-middle">
                    <div class="wrap-policies">
                        <nav aria-label="MIT Libraries policy menu">
                            <span class="item"><a href="https://libraries.mit.edu/privacy" class="link-sub">Privacy</a></span>
                            <span class="item"><a href="https://libraries.mit.edu/permissions" class="link-sub">Permissions</a></span>
                            <span class="item"><a href="https://libraries.mit.edu/accessibility" class="link-sub">Accessibility</a></span>
                        </nav>
                    </div>
                </div>
            </div><!-- end .identity -->
        </div>
    </div>
</div>
<div class="wrap-outer-footer-institute layout-band">
    <div class="wrap-footer-institute">
        <div class="footer-info-institute">
            <a class="link-logo-mit" href="https://www.mit.edu">
              <!--  <img src="https://storia.dh.unica.it/asmsa/sites/default/files/logo_asmsa.png" alt="Massachusetts Institute of Technology"> -->
            </a>
            <div class="license">If you are featured on this site or are a copyright owner of featured content and have copyright or privacy concerns, <a href="https://libraries.mit.edu/research-support/notices/copyright-notify/">notify us</a>.
            </div><!-- end .footer-info-institute -->
        </div>
    </div>
</div>
</footer>
