<div class="wrap-outer-header layout-band">
  <div class="wrap-header">
    <header class="header-site header-slim" role="banner">
      <div class="wrap-header-core">
        <h1 class="name-site group nav-logo">
          <a href="https://storia.dh.unica.it/asmsa" class="logo-mit-lib">
            <span class="sr">MIT Libraries home</span>
            <img src="https://storia.dh.unica.it/asmsa/sites/default/files/logo_asmsa.png" alt="ASMSA">
          </a>
        </h1>
      </div>
      <div class="wrap-header-platform">
        <a href="/" class="platform-name"><?php echo $this->setting('installation_title', 'Omeka S'); ?></a>
      </div>
      <div class="wrap-header-supp">
        <a class="link-logo-mit" href="https://www.mit.edu"><img src="https://storia.dh.unica.it/asmsa/sites/default/files/logo_asmsa.png" alt="ASMSA"></a>
      </div>
    </header>
  </div>
</div>
