<?php
/**
 * This partial relates to the site navigation provided by the theme. This
 * feature is described in the theme documentation at:
 *
 * docs/reference/navigation.md
 */

?>
<div id="navbar-container" class="col1q">
    <nav aria-label="<?php echo $this->escapeHtml($site->title()); ?>">
        <!-- Mobile menu toggle button (hamburger/x icon) -->
        <input id="main-menu-state" type="checkbox" />
        <label class="main-menu-btn" for="main-menu-state">
            <span class="main-menu-btn-icon"></span> Toggle main menu visibility
        </label>
        <?php echo $site->publicNav()->menu(); ?>
    </nav>
</div>
