<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

if ($this->status()->isSiteRequest()) {
    $labelInfo = $this->siteSetting('property_label_information');
    $showLocale = (bool) $this->siteSetting('show_locale_label', true);
    $filterLocale = $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $showValueAnnotations = (bool) $this->siteSetting('show_value_annotations', false);
} else {
    $labelInfo = $this->setting('property_label_information');
    $showLocale = true;
    $filterLocale = false;
    $lang = null;
    $showValueAnnotations = true;
}
$filterLocaleCallback = function ($value) use ($lang) {
    $valueLang = $value->lang();
    return $valueLang == '' || strcasecmp($valueLang, $lang) === 0;
};
?>

<table class="metadata">
    <caption class="sr">Item metadata</caption>
<?php
foreach ($values as $term => $propertyData) :
    $propertyValues = $propertyData['values'];
    if ($filterLocale) {
        $propertyValues = array_filter($propertyValues, $filterLocaleCallback);
    }
    if (!$propertyValues) {
        continue;
    }
    $property = $propertyData['property'];
    $propertyLabel = $propertyData['alternate_label'] ?: $translate($property->label());
    if ('term' === $labelInfo) {
        $propertyTerm = $property->term();
    } elseif ('vocab' === $labelInfo) {
        $propertyTerm = $property->vocabulary()->label();
    } else {
        $propertyTerm = null;
    }
    $propertyRows = count($propertyValues);
    ?>
    <tr class="property">
        <th scope="row" rowspan="<?php echo $propertyRows; ?>">
        <?php echo $escape($propertyLabel); ?>
        <?php if ($propertyTerm !== null) : ?>
        <span class="field-term">(<?php echo $escape($propertyTerm); ?>)</span>
        <?php endif; ?>
        </th>
        <?php foreach ($propertyValues as $key => $value) : ?>
            <?php if (0!=$key) {?>
                </tr><tr>
            <?php } ?>
            <?php
            $valueType = $value->type();
            $valueLang = $value->lang();
            $valueAnnotation = $value->valueAnnotation();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            ?>
        <td class="<?php echo implode(' ', $class); ?>" <?php echo ($valueLang) ? "lang='{$escape($valueLang)}'" : ''; ?>>
            <?php if ($showLocale && $valueLang) : ?>
            <span class="language"><?php echo $valueLang; ?></span>
            <?php endif; ?>
            <span class="value-content"><?php echo $filterLocale ? $value->asHtml($lang) : $value->asHtml(); ?></span>
            <?php if (!$value->isPublic()) : ?>
                <span class="o-icon-private" aria-role="tooltip" title="<?php echo $this->escapeHtml($translate('Private')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Private')); ?>"></span>
            <?php endif; ?>
            <?php if ($valueAnnotation && $showValueAnnotations) : ?>
                <a href="#" class="expand" aria-label="<?php echo $this->escapeHtml($translate('Expand')); ?>">
                    <span class="has-annotation o-icon-annotation" aria-role="tooltip" title="<?php echo $this->escapeHtml($translate('Has annotation')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Has annotation')); ?>"></span>
                </a>
                <div class="collapsible annotation">
                    <?php echo $valueAnnotation->displayValues(); ?>
                </div>
            <?php endif; ?>
            <?php $this->trigger('view.show.value', ['value' => $value]); ?>
        </td>
        <?php endforeach; ?>
    </tr>
<?php endforeach; ?>
</table>
