<?php
$translate = $this->plugin('translate');
$banner_url = $this->themeSettingAssetUrl('banner');
$banner_text = $this->themeSetting('banner_text');
$stylesheet = $this->themeSetting('stylesheet');
$no_search = $this->themeSetting('no_search');

$nav_style = $this->themeSetting('nav_style');
$body_classes = 'nav-horizontal';
$content_classes = 'content-main';
$wrap_classes = 'wrap-content';
if ('vertical' == $nav_style) {
    $body_classes = 'nav-vertical';
    $content_classes .= ' col3q';
    $wrap_classes .= ' layout-1q3q';
}

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('js/smartmenus/dist/css/sm-core-css.css'));
$this->headLink()->appendStylesheet($this->assetUrl('js/smartmenus/dist/css/sm-mint/sm-mint.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/libraries-main.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/base.css'));
if (isset($stylesheet)) {
    $this->headLink()->appendStylesheet($this->assetUrl("css/$stylesheet.css"));
} else {
    // If the site has not chosen a stylesheet, use the Black variant by default.
    $this->headLink()->appendStylesheet($this->assetUrl("css/black.css"));
}
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/smartmenus/dist/jquery.smartmenus.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/tesseract.js'));
$this->headScript()->appendFile($this->assetUrl('js/matomo.js'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="icon" type="image/x-icon" href="<?php echo $this->assetUrl('/img/mitlib-style/favicon.ico'); ?>">
        <?php if ($banner_url) { ?>
            <style>
                .page-banner {
                    background-image: url(<?php echo $banner_url; ?>);
                    background-position: center center;
                    background-repeat: no-repeat;
                    height: 200px;
                }
            </style>
        <?php } ?>
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('class', $body_classes); ?>
        <a id="skip" class="skip sr sr-focusable" href="#content-main">Skip to main content</a>
        <?php echo $userBar; ?>
        <div class="wrap-page">
            <?php echo $this->partial('common/header-site-slim'); ?>
            <div class="wrap-outer-header-local layout-band">
                <div class="page-banner">
                    &nbsp;
                </div>
                <div class="wrap-content">
                    <div class="wrap-header-local">
                        <div class="page-header-home">
                            <a href="<?php echo $site->siteUrl(); ?>">
                                <p class="hd-1"><?php echo $this->escapeHtml($site->title()); ?></p>
                                <?php if ($banner_text) { ?>
                                    <p class="child-tagline"><?php echo $this->escapeHtml($banner_text); ?></p>
                                <?php } ?>
                            </a>
                        </div>
                        <?php if ('default' == $nav_style) { ?>
                            <div class="page-menu">
                                <?php echo $this->partial('common/navigation-default'); ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <?php if (!isset($no_search) || 0 == $no_search) { ?>
                <div class="wrap-outer-search layout-band">
                    <div class="wrap-content">
                        <div class="search">
                            <?php echo $this->partial('common/search-form'); ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="wrap-outer-content layout-band">
                <div class="<?php echo $wrap_classes; ?>">
                    <?php if ('vertical' == $nav_style) { ?>
                        <?php echo $this->partial('common/navigation-vertical'); ?>
                    <?php } ?>
                    <div id="content-main" class="<?php echo $content_classes; ?>" role="main">
                        <?php echo $this->messages(); ?>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <?php echo $this->partial('common/footer-site-slim'); ?>
        </div>
    </body>
</html>
