<?php
$itemSets = [];
switch (get_class($resource)) {
    case 'Omeka\Api\Representation\ItemRepresentation':
        $itemSets = $resource->itemSets();
        $item = $resource;
        break;
    case 'Omeka\Api\Representation\ItemSetRepresentation':
        $itemSets[] = $resource;
        $item = null;
        break;
    default:
        return;
}

if (!$itemSets) {
    return;
}

// Get order for printing hierarchies from Site Hierarchies page setting
$siteHierarchiesArray = $this->siteSetting('site_hierarchies');

$siteGroupings = array();
$printedHierarchies = array();
$groupings = array();
foreach ($itemSets as $itemSet) {
    if (is_numeric($itemSet)) {
        continue;
    }
    $groupings = $api->search('hierarchy_grouping', ['item_set' => $itemSet->id(), 'sort_by' => 'position'])->getContent();
    // Only show groupings/hierarchies assigned by Hierarchy option in site's context menu
    if (is_array($siteHierarchiesArray)) {
        foreach ($siteHierarchiesArray as $siteHierarchy) {
            if (is_array($groupings)) {
                foreach ($groupings as $grouping) {
                    if ($grouping->getHierarchy()->getId() == $siteHierarchy['id']) {
                        if (!in_array($grouping->getHierarchy()->getId(), $printedHierarchies)) {
                            // Only print hierarchies with multiple item set groupings once
                            $siteGroupings[][] = $grouping;
                            $printedHierarchies[] = $grouping->getHierarchy()->getId();
                        }
                    }
                }
            }
        }
    }
}

// Return if no groupings/hierarchies found
if (empty($siteGroupings)) {
    return;
}
?>

<dl class="hierarchies">
    <div class="property">
        <dt><?php echo $this->translate('Hierarchies'); ?></dt>
        <dd class="value">
            <?php if (!empty($siteGroupings) && is_array($siteGroupings)): ?>
                <?php foreach ($siteGroupings as $groupings): ?>
                    <?php if (is_array($groupings)): ?>
                        <?php echo $this->hierarchyHelper()->buildNestedList($groupings, $itemSet, $item, true); ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo $this->translate('No hierarchies to display.'); ?>
            <?php endif; ?>
        </dd>
    </div>
</dl>
