<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="cover-omeka-background">
    <div class="cover-omeka-box">
        <div class="row">
            <div class="column cover-omeka-title">
                <?php echo $title; ?>
            </div>
            <div class="column cover-omeka-text">
                <?php echo $text; ?>
            </div>
        </div>
    </div>
</div>