<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();

// Array of MIME-types supported by ModelViewer.
// For a complete list, see https://github.com/Daniel-KM/Omeka-S-module-ModelViewer#media-types-and-security-issue
$mediaTypes3D = [
    "application/octet-stream",
    "application/vnd.threejs+json",
    "model/gltf-binary",
    "model/gltf+json",
    "model/obj",
    "model/vnd.collada+xml",
    "model/vnd.filmbox",
    "image/ktx2",
    "model/mtl"
];

// Code to determine the class of the resource
if ($item->resourceClass()):
    // Get the resource class label and replace spaces in order to use it in relevant element classes so that display can react.
    $rc=str_replace(" ", "-", strtolower($item->resourceClass()->label()));
else:
    $rc="none";
endif;

$imc=count($itemMedia); //imc =item media count;
$mbc="";
if ($imc>1):
    // if more than one media item, add 'split' to several element classes
    // Note: Currently, only CSS class 'media-embeds.message.split' will be rendered side-by-side
    $mbc = "split";
    //$mbc=mediabox-class
endif;

# Check if this itemMedia contains 3D model
if ($rc == "3dmodel"):
    $model3d = True ;
else:
    $model3d = False ;
endif;

# Extract mediaTypes from all media attached to this item into an array
$mediaTypes = array_map(function($child) {
    return $child->mediaType();
}, $itemMedia);
?>

<div id="item-page">
    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item'); ?></h3>
    <?php $this->trigger('view.show.before'); ?>


    <div id="item-page-media">
        <?php if ($model3d): ?>
            <!-- When 3D model data, render only the 3D itemMedia and skip all other media -->
            <div class="media-embeds">
                <?php foreach ($itemMedia as $media): ?>
                    <?php if (in_array($media->mediaType(), $mediaTypes3D)) : ?>
                        <div class="media-box <?php echo $rc;?>">
                            <div class="media-box-content">
                                <?php echo $media->render();?>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>

        <?php elseif (in_array("application/pdf", $mediaTypes)) : ?>
            <!-- Use the PDF viewer when any of the media is a PDF,  -->
            <div class="media-embeds <?php echo $rc ." ".$mbc ;?>">
                <?php foreach ($itemMedia as $media):?>
                    <div class="media-box <?php echo $rc;?>">
                        <div class="media-box-content">
                            <?php echo $media->render(); ?>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>

        <?php else: ?>
            <!-- Use an IIIF viewer in all other cases -->
            <div class="media-embeds">
                <div class="media-box <?php echo $rc;?>">
                    <div class="media-box-content">
                        <?php
                            if ($this->themeSetting('IiifViewer') == "universal") {
                                echo $this->universalViewer($item);
                            } elseif ($this->themeSetting('IiifViewer') == "mirador") {
                                echo $this->mirador($item);
                            } else {
                                foreach ($itemMedia as $media) {
                                    echo $media->render();
                                }
                            }
                        ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>

    <div id="item-page-properties">
        <div class="properties">

            <?php echo $item->displayValues(); ?>

            <div class="property">
                <!--span style="background-color:red; color:white">values</span-->
                <?php $itemSets = $item->itemSets(); ?>
                <?php if (count($itemSets) > 0): ?>
                    <h4><?php echo $translate('Item sets'); ?></h4>
                    <div class="values">
                        <?php foreach ($itemSets as $itemSet): ?>
                            <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>


    <div id="resources-linked" class="section">
        <?php
        $subjectValues = $item->displaySubjectValues([
            'page' => $this->params()->fromQuery('page', 1),
            'perPage' => 25,
            'resourceProperty' => $this->params()->fromQuery('resource_property'),
        ]);
        ?>

        <?php if ($subjectValues): ?>
            <div id="item-linked">
                <h3><?php echo $translate('Linked resources'); ?></h3>
                <?php echo $subjectValues; ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php $this->trigger('view.show.after'); ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(document).trigger('enhance.tablesaw');
    });
</script>
