<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', $pageBodyClass);
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage) :
    ?>
    <?php if ($activePage['depth'] !== 0) : ?>
    <nav class="breadcrumbs" aria-label="Breadcrumb"><?php echo $nav->breadcrumbs()->setPartial('common/breadcrumbs'); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
    <?php echo $this->partial('common/sites-filter'); ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination) : ?>
    <?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
