<?php
$timestamp=time();
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/mobile.css')); //responsive specific Style behavior (PV-2023-05-08)
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css')); //Generic (institutional?) Style elements
$this->headLink()->prependStylesheet($this->assetUrl('css/search.css')); //Modified Advanced Search style elements of theme (PV-2023-02-06)
//$this->headLink()->prependStylesheet($this->assetUrl('css/sitestyle.css')); //Specific Style Elements.
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Nunito:wght@300&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/desandroimagesloaded.js'));
$this->headScript()->prependFile($this->assetUrl('js/desandromasonry.js'));
$this->headScript()->prependFile($this->assetUrl('js/um_theme.js'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

global $socialCounter;
$arrSocial=[$this->themeSetting('faceBookLink'),
			$this->themeSetting('instaGramLink'),
			$this->themeSetting('linkedInLink'),
			$this->themeSetting('twitterLink'),
			$this->themeSetting('youTubeLink')];
CountSocials($arrSocial);
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
//$summary = $this->pageTitle($site->summary());
//$logo = $this->themeSettingAssetUrl('logo');
$leftLogo = $this->assetUrl('img/logo-um.svg');
//$leftLogo = $this->assetUrl('img/tresoar.png');
$rightLogo = $this->assetUrl('img/right-logo-sample.png');
$footerLogo = $this->assetUrl('img/footer-logo-sample.png');
$facebookLogo=$this->assetUrl('img/facebook.png');
$instagramLogo=$this->assetUrl('img/Instagram.png');
$twitterLogo=$this->assetUrl('img/Twitter.png');
$linkedinLogo=$this->assetUrl('img/LinkedIn.png');
$youtubeLogo=$this->assetUrl('img/Youtube.png');
$topsite = "/";


if($this->themeSetting('UMLogoLink')):
	$topsite=$this->themeSetting('UMLogoLink');
endif;

$userBar = $this->partial('common/user-bar', ['site' => $site]);
$query = $this->params()->fromQuery();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head><meta charset="gb18030">

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php //echo $userBar; ?>
        <header <?php 
        if (strlen($userBar) > 1){ echo "class='logged-in'"; } ?>>
            <div id="top-bar">
		    <div id="Logo-div">
			<a id="institution-logo" 
				href="<?php echo $topsite ?>"><img src="<?php echo $leftLogo ?>" title="Logo" />
			</a>
			<div id="site-header-title"><a href="<?php echo $site->url(); ?>"><?php echo $title; ?></a>
			
		
		</div>	
		</div>
		<div id="header-main">
			<div id="MsgDiv">test</div>
                <nav>
                    <?php echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1]);?>
				
                </nav>
				
				<div id="search-head">
			  <?php 
				$whatPage = $_SERVER['REQUEST_URI'];
				//echo $whatPage;
				$displaySearch = 1;
				if($whatPage=="/" || $whatPage=="/home" || $whatPage=="/index" || $whatPage=="/about" || $whatPage=="/item/search" || $whatPage=="/explore") $displaySearch=0;
				?>
				<?php if($_SERVER['REQUEST_URI'] != $site->url()  && $displaySearch==1){ ?>
					<div id="search" <?php 
				if (strlen($userBar) > 1){ echo "class='logged-in'"; } ?>>
						<!--div id="interior-hero-content"-->
						
						<?php echo $this->partial('search/search-form-simple'); ?>
							<?php //echo $this->partial('common/search-form'); ?>
							<?php //echo $this->hyperlink(); ?>
						<!--/div-->
					</div>
				<?php } ?>
						
				</div>
				
				<div id="nav-about">
				<?php if ($this->themeSetting('supportPage')):?>
			
                    <a href="<?php echo $this->themeSetting('supportPage') ?>" target="_blank">Support</a>
					<?php else: ?>
					<a href="https://library.maastrichtuniversity.nl" target="_blank">Support</a>
				<?php endif; ?>
				</div>
            </div>
		
	
	
		</div>

            
           
			
        </header>
      
        <div id="content" role="main">
            <?php if($_SERVER['REQUEST_URI'] != $site->url()){ ?>
                    <?php echo $this->content; ?>
            <?php } else { ?>         
                <?php echo $this->content; ?>
            <?php } ?>

        </div>
        <?php //if($_SERVER['REQUEST_URI'] != $site->url()){ ?>
            <footer>
			<div class="footer-wrapper">
			
				 <?php if ($this->themeSetting('logoFooter')): ?>
					<div id="footer-logo"><img src="<?php echo $this->themeSettingAssetUrl('logoFooter'); ?>" title="footer logo"></div>
				 <?php endif; ?>
				 <div class="footer-items">
					<?php if ($footerContent = $this->themeSetting('footer')): ?>
					<?php echo $footerContent; ?>
					<?php else: ?>
						<?php echo $this->translate('Powered by Omeka S'); ?>
					<?php endif; ?>
					<div class="footer-col">
				    <?php if($socialCounter>0):?>
					<h3>Follow us on</h3>
						<div class="social">
						<?php echo SocialLink($this->themeSetting('faceBookLink'),$facebookLogo); ?>
						<?php echo SocialLink($this->themeSetting('instaGramLink'),$instagramLogo); ?>
						<?php echo SocialLink($this->themeSetting('linkedInLink'),$linkedinLogo); ?>
						<?php echo SocialLink($this->themeSetting('twitterLink'),$twitterLogo); ?>
						<?php echo SocialLink($this->themeSetting('youTubeLink'),$youtubeLogo); ?>
						</div>
						<?php endif ?>
						</div>	
					
				</div>
				
			</div>
			<div class="footer-bar">
			<div class="footer-bar-wrapper">
			<?php if ($footerBar=$this->themeSetting('footerBar')): ?>
			<?php echo $footerBar; ?>
			<?php endif; ?>
			</div>
			</div>
            </footer>
        <?php //} ?> 
    </body>
</html>
<?php 



function CountSocials($arrSocial)
{
	global $socialCounter;
	$socialCounter=0;
	foreach($arrSocial as $itm)
	if($itm): $socialCounter+=1;
	endif;

}

function SocialLink($ThemeSetting,$logoUrl)
	{
		$result='';
		if ($ThemeSetting):
			$result='<a href="'.$ThemeSetting .'" target="_blank" rel="noopener">'.
			'<img decoding="async" loading="lazy" src="'. $logoUrl.'"/></a>';

		endif;
		return $result;
	}	

?>
