<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$no_advanced_search = $this->themeSetting('no_advanced_search');

$browse_style = $this->themeSetting('browse_style');
if (!isset($browse_style)) {
    $browse_style = "list";
}

$query = $this->params()->fromQuery();
$query_fields = array_keys($query);
sort($query_fields);
$query_fields_without_search = array('page', 'sort_by', 'sort_order');
sort($query_fields_without_search);

$itemSetShow = isset($itemSet);
if ($itemSetShow) :
    $this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
?>

<?php if ($itemSetShow) : ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(null, $valueLang), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $this->resourcePageBlocks($itemSet)->getBlocks(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else : ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<?php if ($query_fields === $query_fields_without_search) { ?>
    <div class="browse-controls">
        <span class="browse-label">Browse by:</span><?php echo $this->browse()->renderSortSelector('items'); ?>
    </div>
<?php } ?>

<?php if (!$no_advanced_search) { ?>
    <p><?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?></p>
<?php } ?>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list <?php echo $browse_style; ?>">
<?php
foreach ($items as $item) :
    echo $this->partial(
        'common/resource-list-item',
        [
            'resource' => $item,
        ]
    );
endforeach;
?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
