<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/explorar.css'));
$this->headScript()->prependFile($this->assetUrl('js/explorar.js'));
?>

<body id="body-explorar">
  <ul class="explorar">
  <li>

<div class="explorsec rutas">

  <h2><a href="/s/catalogo/item-set?resource_template_id[0]=8&sort_by=title&sort_order=asc">Rutas</a>
  </h2>
  <p>Descubrir la colección a través de rutas temáticas</p>
  <a href="#" class="botexp">Rutas actuales</a>

  <div class="explordescr">
    <p>
    <a href="/s/catalogo/item-set/1335?sort_by=dcterms:created&sort_order=desc&page=1">Ruta escultórica por el Campus de Las Lagunillas (Jaén)</a>
    </p>
  </div>
</div>
</li>
    <li>

      <div class="explorsec autorias">

        <h2><a href="/s/catalogo/item-set?resource_template_id%5B0%5D=4&amp;sort_by=title&amp;sort_order=asc&page=1">Autorías</a>
        </h2>
        <p>Las autoras y autores de la colecci&oacute;n Universidad de Ja&eacute;n</p>
        <a href="#" class="botexp">Destacadas</a>

        <div class="explordescr">
          <p>
          <a href="/s/catalogo/item-set/4586">Ángeles Agrela</a>. <a href="/s/catalogo/item-set/5460">Julia Santa Olalla</a>. <a href="/s/catalogo/item-set/4615">Miguel Scheroff</a>. <a href="/s/catalogo/item-set/4611">Leonor Solans</a>. <a href="/s/catalogo/item-set/4713">Santiago Ydáñez</a></p>
        </div>
      </div>
    </li>
    <li>
      <div class="explorsec series">

        <h2><a href="/s/catalogo/item-set?resource_template_id%5B0%5D=5&amp;sort_by=title&amp;sort_order=asc&page=1">Series</a>
        </h2>
        <p>Series tem&aacute;ticas o editoriales que articulan agrupaciones de obras</p>
        <a href="#" class="botexp">Selección</a>

        <div class="explordescr">
          <p>
          <a href="/s/catalogo/item-set/5610?sort_by=dcterms:identifier%5B0%5D=5&amp;sort_order=asc">Caprichos de Goya</a>. <a href="/s/catalogo/item-set/4568?sort_by=dcterms:identifier%5B0%5D=5&amp;sort_order=asc">Del Cantábrico</a>
          </p>
        </div>
      </div>

    </li>

    <li>

<div class="explorsec colecciones">

  <h2><a href="/s/catalogo/item-set?resource_template_id[0]=6&sort_by=title&sort_order=asc&page=1">Colecciones</a>
  </h2>
  <p>Las tres grandes colecciones</p>
  <a href="#" class="botexp">Descubrir</a>

  <div class="explordescr">
    <p>
    <a href="/s/catalogo/item-set/13">Fundación Cesáreo Rodríguez-Aguilera</a>. <a href="/s/catalogo/item-set/3855">Fundación Juan Moral</a>. <a href="/s/catalogo/item-set/5455">Certamen Internacional de Pintura «Manuel Ángeles Ortiz»</a>
    </p>
  </div>
</div>
</li>

<li>

<div class="explorsec etiquetas">

  <h2><a href="/s/catalogo/reference">Etiquetas</a>
  </h2>
  <p>Navegar por la colección por sus etiquetas descriptivas y clasificatorias</p>
  <a href="#" class="botexp">Mostrar</a>

  <div class="explordescr">
    <p>
    <a href="/s/catalogo/reference/fecha">Fecha</a>. <a href="/s/catalogo/reference/tecnica">Técnica</a>. <a href="/s/catalogo/reference/soporte_materia">Soporte o materia</a>. <a href="/s/catalogo/reference/temas">Temas</a>. <a href="/s/catalogo/reference/tipologia">Tipología</a>. <a href="/s/catalogo/reference/estilo">Estilo artístico</a>
    </p>
  </div>
</div>
</li>


  </ul>
</body>