<?php
$value = isset($query['fulltext_search']) ? $query['fulltext_search'] : null;
?>
<div class="field">
    <div class="field-meta">
        <label for="fulltext_search"><?php echo $this->translate('Search full-text'); ?></label>
    </div>
    <div class="inputs">
        <textarea id="fulltext_search" rows="4" name="fulltext_search" class="field field-text field-textarea wide"><?php echo $this->escapeHtml($value); ?></textarea>
    </div>
</div>
